# Site settings
title: Pudhina Fresh
description: >
  A Jekyll theme made for personal websites and blogs. Adapted from Pudhina theme by Knhash.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ritijjain.github.io/pudhina-fresh/" # the base hostname & protocol for your site

author:
  fullname: Pudhina Fresh
  github: 
  linkedin: 
  email: 

disqus_name: 
g_track_id: 

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "_posts"
    values:
      comments: true
      listed: true
      author: Ritij Jain
      author_link: <a href="http://ritijjain.com/">Ritij Jain<a>
  -
    scope:
      path: "pages/redirects"
    values:
      layout: redirect
      index: false
      listed: false