# Site settings
title: Pudhina Fresh
short_logo: P.
description: >
  A minimal yet feature-rich Jekyll theme made for personal websites and blogs.
baseurl: "/pudhina-fresh" # The subpath of your site, e.g. /blog/.
url: "https://ritijjain.github.io" # The base hostname & protocol for your site.

author:
  fullname: Ritij Jain
  github: /ritijjain/pudhina-fresh
  linkedin: /
  email: /

disqus_name: 
g_track_id: 

markdown: kramdown

defaults:
  -
    scope:
      path: _posts
    values:
      comments: true
      listed: true
      author: Ritij Jain
      author_link: <a href="https://ritijjain.com/">Ritij Jain<a>
  -
    scope:
      path: pages/redirects
    values:
      layout: redirect
      index: false # When false, <meta name="robots" content="noindex"> is added to the page.
      listed: false # Defines if page is listed on the sitemap.
  -
    scope:
      path: pages/tags
    values:
      layout: tag
      index: false # When false, <meta name="robots" content="noindex"> is added to the page.
      listed: false # Defines if page is listed on the sitemap.